micronaut:
  server:
    cors:
      enabled: true
  application:
    name: society_maintenance
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    intercept-url-map:
      # Allow React login page
      - pattern: /
        access:
          - isAnonymous()
      - pattern: /login
        access:
          - isAnonymous()

      # Allow static resources (JS, CSS, etc.)
      - pattern: /static/**
        access:
          - isAnonymous()
      - pattern: /favicon.ico
        access:
          - isAnonymous()

      # Allow your auth API endpoint
      - pattern: /api/auth/login
        access:
          - isAnonymous()

      # Protect everything else
      - pattern: /api/**
        access:
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui

datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.containers.internal:5432/mydatabase
    username: myuser
    password: strongpassword

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update