micronaut:
  server:
    cors:
      enabled: true
  application:
    name: society_maintenance
  security:
    authentication: bearer
    intercept-url-map:
      - pattern: /
        access: isAnonymous()
      - pattern: /swagger/**
        access: isAnonymous()
      - pattern: /swagger-ui/**
        access: isAnonymous()
      - pattern: /v3/api-docs/**
        access: isAnonymous()
      - pattern: /api/**
        access: isAuthenticated()
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
        generator:
          refresh-token:
            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
      default:
        mapping: /**
        paths: classpath:static
        default-file: index.html

datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.containers.internal:5432/mydatabase
    username: myuser
    password: strongpassword

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update